import type { Metadata } from "next";
import "./styles/globals.css";
import { Baloo_Chettan_2 } from "next/font/google";

const baloo = Baloo_Chettan_2({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${baloo.className} bg-orange-50`}>{children}</body>
    </html>
  );
}
